version: '3.8'

services:
  Deep-Batch-Swapper:
    container_name: batch-faceswap
    image: docker.io/avgradmin/deep-swap:v0.1.2-cuda-12.2
    build:
      context: .
      dockerfile: docker/Dockerfile.cuda12-2  
    environment:
      ## Processor
      - MANY_FACES=true  # true/false
      - frame_processor={face_swapper,face_enhancer}
      ## Performance
      - max_mem=16
      - threads=4
      - video_encoder=libx265
      - keep_fps=true
      - keep_audio=true
      - also_enhance_face=true
      - USE_GPU=cuda  # Change to cuda or whatever you need to use. 'false' disables.
      ## Video
      - USE_VIDEO_ARGS=false  # true/false
      - video_quality=0

      - NVIDIA_VISIBLE_DEVICES=1 
      # Display
      - DISPLAY=$DISPLAY
    volumes:
    # Change according to your setup
      - ./:/app
      # Do not change below volumes
      - ./run.sh:/app/docker_script.sh
      - ./models/.insightface:/root/.insightface
      - ./models/.insightface:/app/.insightface
      - ./models/gfpgan:/app/gfpgan
      - ./models:/app/models
      - ./output:/app/output


      # Display
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    privileged: true # Need for webcam
    runtime: nvidia
    command: [ "/bin/bash", "/app/docker_script.sh" ]
  
